"""first

Revision ID: 8480c132b1f7
Revises: 
Create Date: 2021-10-25 18:52:52.229752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8480c132b1f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
